# Default structure isready.toml files should follow. This file contains all supported checks.

[project]
name = "isready"

[[check]]
name = "Check if ssh server is up"
type = "tcp"
host = "localhost"
port = 22
# Timeout in seconds
timeout = 10

[[check]]
name = "Check 'HOME' env"
type = "env"
var = "HOME"

[[check]]
name = "Check if the binary 'ls' exists"
type = "binary"
executable = "ls"