# Default structure isready.toml files should follow. This file contains all supported checks.

# [project] - contains config about current project
# [[check]] - config about a check.

[project]
name = "isready"

[[check]]
name = "Check if ssh server is up"
type = "tcp"
host = "localhost"
port = 22
# Timeout in seconds
timeout = 10

[[check]]
name = "Check 'HOME' env"
type = "env"
var = "HOME"

[[check]]
name = "Check if the binary 'ls' exists"
type = "binary"
executable = "ls"
# Optional args config
args = ["-lh"]
# Output output config - "true" to show command output, or "false" to not show it
output = false